[package]
name = "{% name %}"
version = "{% version %}"

[build]
api = "CoreEngine"
launcher = "launcher.js"

[assets]
gui = "assets/gui"
resources = "assets/resources"
behavior-packs = "assets/behavior_packs"
resource-packs = "assets/resource_packs"
